# Generated by Django 3.1.13 on 2021-11-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the thumbnail type')),
                ('img_height', models.IntegerField(verbose_name='Image height')),
                ('img_width', models.IntegerField(blank=True, null=True, verbose_name='Image width')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the user image')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Account Plan')),
                ('original_file_access', models.BooleanField(default=False, verbose_name='Original file access')),
                ('expiring_links_access', models.BooleanField(default=False, verbose_name='Expiring links access')),
                ('thumbnail_types', models.ManyToManyField(to='photo_host.ThumbnailType')),
            ],
        ),
    ]
