# Generated by Django 3.1.13 on 2021-11-19 16:28

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo_host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='ser_images/', verbose_name='Image'),
        ),
    ]
